name: Falco distribution check on Ubuntu

on:
  workflow_dispatch:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Update packages
      run: sudo apt-get update
    - name: Install dependencies
      run: sudo apt-get install -y libhts-dev
    - name: Generate configure script
      run: ./autogen.sh
    - name: configure
      run: ./configure --enable-hts
    - name: Build falco
      run: make
    - name: Check the distribution
      run: make distcheck
    - name: Cleanup after the build
      run: make distclean
